---
title: "Supplemental Material for Adaptive phenotypic plasticity stabilizes evolution in fluctuating environments"
author: "Alexander Lalejini, Austin J. Ferguson, Nkrumah A. Grant, and Charles Ofria"
date: "`r Sys.Date()`"
output: bookdown::gitbook
documentclass: book
bibliography: ["packages.bib", "supplemental.bib"]
biblio-style: apalike
nocite: '@*'
link-citations: yes
github-repo: amlalejini/evolutionary-consequences-of-plasticity
description: "Supplemental material"
---

# Introduction

This is the supplemental material for our work entitled, _Adaptive phenotypic plasticity stabilizes evolution in fluctuating environments_.
Preprint forthcoming.

## About our supplemental material

This supplemental material is hosted on [GitHub](https://github.com/) using GitHub pages.
The source code and configuration files used to generate this supplemental material can be found in [this GitHub repository](https://github.com/amlalejini/evolutionary-consequences-of-plasticity).
We compiled our data analyses and supplemental documentation into this nifty web-accessible book using [bookdown](https://bookdown.org/).

Our supplemental material includes the following:

- Data availability (Section \@ref(data-availability))
- Guide for running our experiments (Section \@ref(compile-and-run-experiments-locally))
- Avida instruction set (Section \@ref(avida-instruction-set))
- Experiment analyses (including source code):
  - Validating the evolution of phenotypic plasticity (Section \@ref(validation-experiment))
  - Effect of adaptive phenotypic plasticity on evolutionary change (Section TODO)
    - Results with variable-length genomes (Section TODO)
  - Effect of adaptive phenotypic plasticity on the evolution and maintenance of novel traits (Section TODO)
  - Effect of adaptive phenotypic plasticity on the accumulation of deleterious instructions (Section TODO)
  - Exploring how regulation is encoded in genomes in Avida (Section TODO)

## Contributing authors

- [Alexander Lalejini](https://lalejini.com/)
- [Austin J. Ferguson](http://austinjferguson.com/)
- Nkrumah A. Grant
- [Charles Ofria](https://ofria.com/)

## Research overview

Abstract:
> Fluctuating environmental conditions are ubiquitous in natural systems, and populations have evolved various strategies to cope with such fluctuations.
The particular mechanisms that evolve profoundly influence subsequent evolutionary dynamics.
One such mechanism is phenotypic plasticity, which is the ability of a single genotype to produce alternate phenotypes in an environmentally dependent context.
Here, we use digital organisms (self-replicating computer programs) to investigate how adaptive phenotypic plasticity alters evolutionary dynamics and influences evolutionary outcomes in cyclically changing environments.
Specifically, we examined the evolutionary histories of both plastic populations and non-plastic populations to ask:
(1) Does adaptive plasticity promote or constrain evolutionary change?
(2) Are plastic populations better able to evolve and then maintain novel traits?
And (3), how does adaptive plasticity affect the potential for maladaptive traits to accumulate in evolving genomes?
We find that populations with adaptive phenotypic plasticity undergo less evolutionary change than non-plastic populations, which must rely on genetic variation from de novo mutations to continuously readapt to environmental fluctuations.
Indeed, the non-plastic populations undergo more frequent selective sweeps and accumulate many more genetic changes.
We find that the repeated selected sweeps in non-plastic populations drive the loss of beneficial traits via deleterious hitchhiking, whereas phenotypic plasticity can stabilize populations against environmental fluctuations.
This stabilization allows plastic populations to more easily retain novel adaptive traits than their non-plastic counterparts.
In general, the evolution of adaptive phenotypic plasticity shifted evolutionary dynamics to be more similar to that of populations evolving in a static environment than to non-plastic populations evolving in an identical fluctuating environment.
All natural environments subject populations to some form of change; our findings suggest that the stabilizing effect of phenotypic plasticity plays an important role in subsequent adaptive evolution.
