---
title: "2020-09-21 Experiment Analysis"
output:
  html_document:
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
    code_folding: hide
  pdf_document:
    toc: true
    toc_depth: 4
---

## Analysis Dependencies

```{r, message=FALSE}
library(ggplot2)   # (Wickham, 2016)
library(tidyr)     # (Wickham and Henry, 2020)
library(dplyr)     # (Wickham et al., 2020)
library(reshape2)  # (Wickham, 2007)
library(cowplot)   # (Wilke, 2019)
library(patchwork) # (Pederson, 2020)
library(viridis)   # (Garnier, 2018)
library(hexbin)
```

We conducted these analyses using the following computing environment:

```{r}
print(version)
```

## Setup

```{r}
data_path <- "./data/aggregate.csv"
agg_data <- read.csv(data_path, na.strings="NONE")

agg_data$DISABLE_REACTION_SENSORS <- as.factor(agg_data$DISABLE_REACTION_SENSORS)
agg_data$env_cond <- factor(
  agg_data$env_cond,
  levels=c("a-u0", "b-u0", "all-u0",
           "chg-u3", "chg-u10","chg-u30",
           "chg-u100","chg-u300","chg-u1000")
)
agg_data$chg_env <- as.factor(agg_data$chg_env)

agg_data$hitchhiker <- as.factor(agg_data$hitchhiker)
agg_data$hitchhiker_magnitude <- as.factor(agg_data$hitchhiker_magnitude)

agg_data$phase <- as.factor(agg_data$phase)
agg_data$dom_plastic_odd_even <- as.factor(agg_data$dom_plastic_odd_even)
agg_data$sensors <- agg_data$DISABLE_REACTION_SENSORS == "0"


theme_set(theme_cowplot())

prob_die_data <- filter(agg_data, hitchhiker == "prob-die")
poison_data <- filter(agg_data, hitchhiker == "poison")

```

## Graphs!

```{r}
ggplot(prob_die_data, aes(x=sensors, fill=sensors)) +
  geom_bar(position=position_dodge(0.9)) +
  geom_text(
    stat="count",
    mapping=aes(label=..count..),
    position=position_dodge(0.9), vjust=0
  )  +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  ylab("number of phase 2 runs") +
  ylim(0, 105) +
  facet_grid(hitchhiker_magnitude~env_cond) +
  ggtitle("prob-die Made it to phase 2?") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/num_runs_prob_die.pdf", width=10, height=10)

ggplot(poison_data, aes(x=sensors, fill=sensors)) +
  geom_bar(position=position_dodge(0.9)) +
  geom_text(
    stat="count",
    mapping=aes(label=..count..),
    position=position_dodge(0.9), vjust=0
  )  +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  ylab("number of phase 2 runs") +
  ylim(0, 105) +
  facet_grid(hitchhiker_magnitude~env_cond) +
  ggtitle("poison Made it to phase 2?") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/num_runs_poison.pdf", width=10, height=10)
```

```{r}
ggplot(filter(prob_die_data), aes(x=sensors, y=genome_length, color=sensors)) +
  geom_boxplot() +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/prob_die_genome_length.pdf", width=10, height=7)

ggplot(filter(poison_data), aes(x=sensors, y=genome_length, color=sensors)) +
  geom_boxplot() +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/poison_genome_length.pdf", width=10, height=7)
```

```{r}
ggplot(filter(prob_die_data), aes(x=sensors, y=pop_inst_count_prob.die, color=sensors)) +
  geom_boxplot() +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/prob_die_inst_cnt.pdf", width=10, height=7)

ggplot(filter(prob_die_data), aes(x=sensors, y=pop_inst_count_nop.x, color=sensors)) +
  geom_boxplot() +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/nopx_prob_die_inst_cnt.pdf", width=10, height=7)

ggplot(filter(poison_data), aes(x=sensors, y=pop_inst_count_poison, color=sensors)) +
  geom_boxplot() +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE), labels=c("T","F")) +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  ggsave("plots/poison_inst_cnt.pdf", width=10, height=7)
```

```{r}

ggplot(filter(prob_die_data), aes(x=genome_length, y=pop_inst_count_prob.die, color=sensors)) +
  geom_jitter() +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) 

ggplot(filter(poison_data), aes(x=genome_length, y=pop_inst_count_poison, color=sensors)) +
  geom_jitter() +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) 

ggplot(filter(poison_data), aes(x=genome_length, y=pop_inst_count_nop.x, color=sensors)) +
  geom_jitter() +
  facet_grid(hitchhiker_magnitude~env_cond, scales = "free_y") +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2)) 

```