---
title: "2020-08-17 Experiment Analysis"
output:
  html_document:
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
    code_folding: hide
  pdf_document:
    toc: true
    toc_depth: 4
---

## Analysis Dependencies

```{r, message=FALSE}
library(ggplot2)   # (Wickham, 2016)
library(tidyr)     # (Wickham and Henry, 2020)
library(dplyr)     # (Wickham et al., 2020)
library(reshape2)  # (Wickham, 2007)
library(cowplot)   # (Wilke, 2019)
library(patchwork) # (Pederson, 2020)
library(viridis)   # (Garnier, 2018)
library(hexbin)
```

We conducted these analyses using the following computing environment:

```{r}
print(version)
```

## Setup

```{r}
data_path <- "./data/aggregate.csv"
agg_data <- read.csv(data_path, na.strings="NONE")

agg_data$DISABLE_REACTION_SENSORS <- as.factor(agg_data$DISABLE_REACTION_SENSORS)
agg_data$change_rate <- as.factor(agg_data$change_rate)
agg_data$changing_env <- as.factor(agg_data$changing_env)
agg_data$plastic_odd_even <- as.factor(agg_data$plastic_odd_even)

agg_data$sensors <- agg_data$DISABLE_REACTION_SENSORS == "0"

```

## Graphs!

### Plasticity

```{r}
ggplot(filter(agg_data, plastic_odd_even=="True"), aes(x=sensors)) +
  geom_bar(position=position_dodge(0.9)) +
  geom_text(
    stat="count",
    mapping=aes(label=..count..),
    position=position_dodge(0.9), vjust=0
  )  +
  scale_x_discrete(name="Sensors", limits=c(TRUE, FALSE)) +
  ylab("plastic final dominant (odd/even environment)") +
  facet_wrap(~change_rate) +
  ggsave("final_dom_plastic.pdf")
```

### Equals

```{r}
ggplot(filter(agg_data, equals=="True"), aes(x=sensors)) +
  geom_bar(position=position_dodge(0.9)) +
  geom_text(
    stat="count",
    mapping=aes(label=..count..),
    position=position_dodge(0.9), vjust=0
  )  +
  ylab("Replicates w/equals-capable final dom") +
  facet_wrap(~change_rate) + 
  ggsave("equals_final_dom.pdf")
```

```{r}
# agg_data$plastic_along_lineage = agg_data$plastic_odd_even_generation != "None"
ggplot(filter(agg_data, equals_update!="None"), aes(x=sensors)) +
  geom_bar(position=position_dodge(0.9)) +
  geom_text(
    stat="count",
    mapping=aes(label=..count..),
    position=position_dodge(0.9), vjust=0
  )  +
  ylab("Replicates w/Equals Along Lineage") +
  facet_wrap(~change_rate) + 
  ggsave("equals_on_lineage.pdf")
```


```{r}
ggplot(filter(agg_data), aes(x=sensors, y=match_score_odd_even)) +
  geom_boxplot()  +
  facet_wrap(~change_rate) 
```

```{r}
agg_data_equals_odd_even = filter(agg_data, equals_odd.even_generation!="None")
agg_data_equals_odd_even$equals_odd.even_generation <- as.numeric(agg_data_equals_odd_even$equals_odd.even_generation)
agg_data_equals_odd_even$equals_odd.even_update <- as.numeric(agg_data_equals_odd_even$equals_odd.even_update)

ggplot(agg_data_equals_odd_even, aes(x=sensors, y=equals_odd.even_update)) +
  geom_boxplot()  +
  facet_wrap(~change_rate) 
```

```{r}
ggplot(agg_data, aes(x=sensors, y=lineage_length)) +
  geom_boxplot()  +
  facet_wrap(~change_rate) + ggsave("lineage_length.pdf")

ggplot(agg_data, aes(x=sensors, y=average_generation)) +
  geom_boxplot()  +
  facet_wrap(~change_rate) + ggsave("average_generation.pdf")
```